### ISSUE TITLE
[Feature] Twig-style Macros

### ISSUE THREAD

**Issue by paularmstrong** [skid/node-t#5]
In [Twig](http://www.twig-project.org), there is a concept of [macros](http://www.twig-project.org/doc/templates.html#macros): template-defined shortcuts for commonly used elements.

Here's an example straight from the Twig documentation:

```
{% macro input(name, value, type, size) %}
    <input type="{{ type|default('text') }}" name="{{ name }}" value="{{ value|e }}" size="{{ size|default(20) }}" />
{% endmacro %}
```

I always found these incredibly useful when building larger sites and apps, as they allowed me to define how the markup around form elements should always be, allowing me to write less HTML–and write it faster.

Thoughts on adding this?

**Comment by skid** [comment]
I initially developed node-t to use it on a project of mine that would allow widgets depending on dynamic data to be incorporated in pages. If you take a look at the _slot_/_widget_ feature of node-t - it pretty much does the same thing as the macros, the difference being that you define your HTML as strings within the javascript widget code.

I admit that separating the HTML from logic is a good thing but since node-t is a sandboxed template engine, it can't be as flexible as a javascript function that outputs HTML . For instance, how would you define a macro that recursively prints out a tree structure?

We'll also need a better lexer since we're introducing new syntax, but that's needed anyway for other tags and filters.

Finally, i suppose that if you define a macro in a template, it will only be accessible in that template. To have it accessible everywhere, you would need to put it in a separate "macros.html" template and then import it, which is not much different than having a separate "widgets.js" file that contains functions that output HTML.

In any case, it's probably a good idea. If other people start using node-t, i bet they'll find it useful. If you code a macro tag, I'll merge it and probably use it for cases when there are repeating patterns in a single template, but for the project I'm working on, I'll mainly stick to the slot/widget idea.

**Comment by paularmstrong** [comment]
Yeah, I understand the idea of slots/widgets, but they seem a bit more difficult to write than just dropping some HTML somewhere. However, making them work the way that Twig works will be a pretty big overhaul, since, as you said, they would currently have to be defined per each template and wouldn't just work out of the box globally.

Maybe slots/widgets work just fine–if we were to add in parameters for them that could be passed from the templates themselves, like `{% slot input('text', 'frame', 'First Name') %}`.

Maybe `slot` is the wrong term for them if they were changed to go that route.
